name: meowskin
description: AI-powered cat skin disease detection app.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI and responsive design
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.1
  
  # Feature dependencies
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  http: ^1.1.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/models/cat_skin_efficientnetv2s.onnx

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

#cd catskin_detector
#flutter pub get